name: stats

on:
    push:
      branches: [ main]
    pull_request:
      branches: [ main ]
      
jobs:
      
    cloc:
      runs-on: ubuntu-latest
      name: A job to count the lines of code.
      permissions:
        id-token: write 
        contents: write
      steps:
        - name: Count lines
          uses: actions/checkout@v4
        - name: Get the lines of code.
          id: cloc
          uses: djdefi/cloc-action@6
          with:
            options: ${{ env.workspace }} --exclude-dir=docs,LICENSE,testdata --exclude-ext=md --out=cloc.json --no-autogen . 

        - name: Check
          run: echo ${{ toJson(steps.cloc.outputs) }}
        - name: Write Badge
          uses: action-badges/core@0.3.0
          with:
            file-name: lines.svg
            github-token: "${{ secrets.GITHUB_TOKEN }}"
            badge-branch: badges
            label: code lines
            message: ${{ toJson('cloc.json')[1].code }}
            message-color: blue
